<div class="buttons">
    <h2 class="title">Buttons</h2>
    <div class="row">
        <div class="col">
            <button class="btn secondary" type="button">
                <span>ADD TO CART</span>
            </button>
            <button class="btn secondary" type="button" :hover >
                <span>ADD TO CART</span>
            </button>
        </div>

        <div class="col">
            <button class="btn secondary standard" type="button">
                <span>STANDARD</span>
            </button>
            <button class="btn secondary standard" type="button" :hover >
                <span>STANDARD</span>
            </button>
        </div>

        <div class="col">
            <div class="spinner">
                <span class="sub">-</span>
                    <input class="btn-nb" type="number" value="1" step="1" min="1" max="15">
                <span class="add">+</span>
            </div>

            <div class="spinner">
                <span class="sub">-</span>
                    <input class="btn-nb" type="number" value="1" step="1" min="1" max="15">
                <span class="add">+</span>
            </div>   
        </div>
    </div>
</div>

<div class="buttons-input">
    <h2 class="title">Checkboxes & Radio Buttons</h2>
    <div class="row">
        <div class="col">
            <input type="checkbox" id="ck1" checked  name="cb" value="" >
            <label for="ck1"> Ticked</label><br/>
            <input type="checkbox" id="ck2" name="cb" value="" >
            <label for="ck2"> Not Ticked</label><br/>
            <input type="checkbox" id="ck3" disabled="disabled" checked name="cb" value="" >
            <label for="ck3"> Ticked, Disabled</label><br/>
            <input type="checkbox" id="ck4" disabled="disabled"  name="cb" value="" >
            <label for="ck4"> Disabled</label>
        </div>
        <div class="col">
            <input type="radio" id="rd1" checked name="rd" value="" />
            <label for="rd1"> Selected</label><br/>
            <input type="radio" id="rd2" name="rd" value="" >
            <label for="rd2"> Not Selected</label><br/>
            <input type="radio" id="rd3" disabled="disabled" checked name="rd2" value="" />
            <label for="rd3"> Selected, Disabled</label><br/>
            <input type="radio" id="rd4" disabled="disabled" name="rd2" value="" />
            <label for="rd4"> Disabled</label>
        </div>
    </div>

</div>

<div class="input-field">
    <h2 class="title">Input Fields</h2>
    <form class="form" action="" method="post" data-hasrequired="* Required Fields">
        <fieldset class="fieldset">
            <div class="field-input">
                <div class="control">
                    <select class="input" name="select" id="select">
                        <option value="">Dropdown field</option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                    </select>
                </div>
</br>
                <div class="control">
                    <input type="text" class="input" data-validate='{"required":true}' data-msg-required="Please select size." placeholder="Text field" name="input" />
                </div>
</br>
                <div class="control">
                    <input type="text" class="input" placeholder="Text field" name="input" value="">
                </div>
</br>
                <div class="control">
                    <input type="email" class="input" placeholder="Please enter the email" name="email" value="">
                </div>
            </div>
        </fieldset>
        <div class="actions-toolbar">
	        <div class="primary">
            		<input type="hidden" name="hideit" id="hideit" value="" />
            		<button type="submit" title="Submit" class="action submit primary">
                		<span>Submit</span>
            		</button>
        	</div>
    	</div>
    </form>
</div>

<div class="navigations">
    <h2 class="title">Navigation</h2>
    <dl class="section-navigation" data-sections="tabs" data-mage-init='{"mage/tabs": {"openedState": "active", "animate": {"duration": 100}, "active": 0,  "disabledState": "disabled"}}'>
        <dt class="item title" data-section="title" data-role="collapsible">
            <a class="switch" data-toggle="trigger" href="#product_description">Description</a>
        </dt>
        <dd id="product_description" class="item content active" data-role="content">
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
        </dd>

        <dt class="item title" data-section="title" data-role="collapsible">
            <a class="switch" data-toggle="trigger" href="#product_tags">Specifications</a>
        </dt>
        <dd id="product_tags" class="item content" data-role="content">
            <p>It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
        </dd>

        <dt class="item title" data-section="title" data-role="collapsible">
            <a class="switch" data-toggle="trigger" href="#product_reviews">FAQ</a>
        </dt>
        <dd id="product_reviews" class="item content" data-role="content">
            <p>It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
        </dd>
  </dl>
    
</div>
