<div class="alert">
    <h2 class="title">Alerts</h2>
    <div class="alert-success">
        <p>Product has been added to your shopping bag</p>
    </div>
    <div class="alert-error">
        <p>Invalid username or password</p>
    </div>
</div>

<div class="typography">
    <h2 class="title">Typography</h2>
    <p>Open Sans Regular - 13px / 20px<p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
    Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. 
    Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</br>
</br>
    <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, 
    totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
</br>
</br>
    <a href="#">Text link</a>
</br>
    <a href="#">Text link hover</a>
</br>
</br>
</br>
    <h1>h1 Lora Regular - 32px</h1>
    <h2>h2 Lora Regular - 24px</h2>
    <h3>h3 Lora Regular - 18px</h3>
    <h4>h4 Lora Regular - 15px</h4>
</div>

<div class="misc">
    <h2 class="title">Misc</h2>
    
</div>

