<div class="main-banner">
    <?php 
        echo $block->getLayout()
                    ->createBlock('Magento\Cms\Block\Block')
                    ->setBlockId('main-banner')
                    ->toHtml();
    ?>
</div>

<!-- <div class="banner-section">
    <h1>Outdoor Dining</h1>
    <h2>Get summer ready with our exclusive outdoor furniture</h2>
    <a class="action primary" href="#">Shop outdoor Daybeds<span><i class="fas fa-chevron-right"></i></span></a>
</div> -->