<!-- <div class="tiles">
    <div class="sub-tile">
        <div class="tile-img">
            <p>BBBB</p>
        </div>
        <h2 class="tile-title"><span>OUTDOOR DINING</span></h2>
        <a href="#" class="tile-link"><span>SHOW NOW</span></a>
    </div>

    <div class="sub-tile">
        <div class="tile-img">
            <p>BBBB</p>
        </div>
        <h2 class="tile-title"><span>OUTDOOR DINING</span></h2>
        <a href="#" class="tile-link"><span>SHOW NOW</span></a>
    </div>
</div>

<div class="reason-to-buy">
    <a href="#" class="reason-to-buy__link"><span>abc</span></a>
    <a href="#" class="reason-to-buy__link"><span>abc</span></a>
    <a href="#" class="reason-to-buy__link"><span>abc</span></a>
</div>

<div class="banner-mid">
    <div class="sub-banner-mid">
        <div class="banner-mid-img">
            <img src="#" alt="AAA">
        </div>
        <div class="banner-mid-title">
            <h2>Collection</h2>
        </div>
        <div class="banner-mid-describe">
            <p>Loremsa</p>
        </div>
        <a href="#" class="banner-mid-link">SHOP NOW<span>></span></a>
    </div>

    <div class="sub-banner-mid">
        <div class="banner-mid-img">
            <img src="#" alt="AAA">
        </div>
        <div class="banner-mid-title">
            <h2>Collection</h2>
        </div>
        <div class="banner-mid-describe">
            <p>Loremsa</p>
        </div>
        <a href="#" class="banner-mid-link">SHOP NOW<span>></span></a>
    </div>

    <div class="sub-banner-mid">
        <div class="banner-mid-img">
            <img src="#" alt="AAA">
        </div>
        <div class="banner-mid-title">
            <h2>Collection</h2>
        </div>
        <div class="banner-mid-describe">
            <p>Loremsa</p>
        </div>
        <a href="#" class="banner-mid-link">SHOP NOW<span>></span></a>
    </div>
</div>

<div class="tiles">
    <div class="sub-tile">
        <div class="tile-img">
            <p>BBBB</p>
        </div>
        <h2 class="tile-title"><span>OUTDOOR DINING</span></h2>
        <a href="#" class="tile-link"><span>SHOW NOW</span></a>
    </div>

    <div class="sub-tile">
        <div class="tile-img">
            <p>BBBB</p>
        </div>
        <h2 class="tile-title"><span>OUTDOOR DINING</span></h2>
        <a href="#" class="tile-link"><span>SHOW NOW</span></a>
    </div>
</div>

<div class="list-best-sellers">
    <p>ABB</p>
</div>

<div class="list-arrivals">
    <p>ABB</p>
</div>

<div class="list-shop-instagrams">
    <ul class="list-instagrams">
        <li class="sub-instagram">a</li>
        <li class="sub-instagram">b</li>
        <li class="sub-instagram">c</li>
        <li class="sub-instagram">a</li>
        <li class="sub-instagram">d</li>
    </ul>
</div>

<div class="shop-blog">
    <div class="sub-blog">
        <div class="sub-blog-img">
            <p>AAA</p>
        </div>

        <div class="blog-introduce">
            <h3 class="blog-title"><span>A</span></h3>
            <p class="blog-describe"><span>abc</span></p>
            <a class="blog-link" href="#"><span>View more</span></a>
        </div>
    </div>

    <div class="sub-blog">
        <div class="sub-blog-img">
            <p>AAA</p>
        </div>

        <div class="blog-introduce">
            <h3 class="blog-title"><span>A</span></h3>
            <p class="blog-describe"><span>abc</span></p>
            <a class="blog-link" href="#"><span>View more</span></a>
        </div>
    </div>

    <div class="sub-blog">
        <div class="sub-blog-img">
            <p>AAA</p>
        </div>

        <div class="blog-introduce">
            <h3 class="blog-title"><span>A</span></h3>
            <p class="blog-describe"><span>abc</span></p>
            <a class="blog-link" href="#"><span>View more</span></a>
        </div>
    </div>

    <div class="sub-blog">
        <div class="sub-blog-img">
            <p>AAA</p>
        </div>

        <div class="blog-introduce">
            <h3 class="blog-title"><span>A</span></h3>
            <p class="blog-describe"><span>abc</span></p>
            <a class="blog-link" href="#"><span>View more</span></a>
        </div>
    </div>

    <div class="sub-blog">
        <div class="sub-blog-img">
            <p>AAA</p>
        </div>

        <div class="blog-introduce">
            <h3 class="blog-title"><span>A</span></h3>
            <p class="blog-describe"><span>abc</span></p>
            <a class="blog-link" href="#"><span>View more</span></a>
        </div>
    </div>

    <div class="sub-blog">
        <div class="sub-blog-img">
            <p>AAA</p>
        </div>

        <div class="blog-introduce">
            <h3 class="blog-title"><span>A</span></h3>
            <p class="blog-describe"><span>abc</span></p>
            <a class="blog-link" href="#"><span>View more</span></a>
        </div>
    </div>

</div>

<div class="testimonials">
    <div class="sub-testimonial">
        <p class="testimonial-describe">abc <a href="#"><span>View more</span></a></p>
        <strong class="testimonial-author"><span>Rebecca</span></strong>
        <p class="testimonial-date"><span>November 17,2016</span></p>
    </div>

    <div class="sub-testimonial">
        <p class="testimonial-describe">abc <a href="#"><span>View more</span></a></p>
        <strong class="testimonial-author"><span>Rebecca</span></strong>
        <p class="testimonial-date"><span>November 17,2016</span></p>
    </div>

    <div class="sub-testimonial">
        <p class="testimonial-describe">abc <a href="#"><span>View more</span></a</p>
        <strong class="testimonial-author"><span>Rebecca</span></strong>
        <p class="testimonial-date"><span>November 17,2016</span></p>
    </div>

    <div class="sub-testimonial">
        <p class="testimonial-describe">abc <a href="#"><span>View more</span></a></p>
        <strong class="testimonial-author"><span>Rebecca</span></strong>
        <p class="testimonial-date"><span>November 17,2016</span></p>
    </div>
</div> -->

<!-- <div class="sub-footer-middle" data-mage-init='{
        "accordion":{
            "active": [1, 2],
            "collapsible": true,
            "openedState": "active",
            "multipleCollapsible": true
        }}'>
<div data-role="collapsible">
<div data-role="trigger">
        <h2>Categories</h2>
</div>
</div>
<div data-role="content">
<ul class="footer-links">
<li class="sub-link"><a href="#">Outdoor Lounges</a></li>
<li class="sub-link"><a href="#">Outdoor Dining</a></li>
<li class="sub-link"><a href="#">Outdoor Umbrellas &amp; Accessries</a></li>
<li class="sub-link"><a href="#">Wood Fireplaces</a></li>
<li class="sub-link"><a href="#">Gas Fireplaces</a></li>
<li class="sub-link"><a href="#">Ethanol Fireplaces</a></li>
<li class="sub-link"><a href="#">Ethanol Fireplaces</a></li>
<li class="sub-link"><a href="#">Weber Charcoal BBQs</a></li>
<li class="sub-link"><a href="#">Weber Premium Gas BBQs</a></li>
<li class="sub-link"><a href="#">Weber Qs</a></li>
<li class="sub-link"><a href="#">Weber Elelectic BBQs</a></li>
<li class="sub-link"><a href="#">Clearance Store</a></li>
</ul>
</div>
</div> -->

<!--
-------------------------------------------------------------------------------------------    
<div class="sub-footer-middle" >
    <div data-role="collapsible">
        <div data-role="trigger">
                <h2>Categories</h2>
        </div>
    </div>
    <div data-role="content">
        <ul class="footer-links">
            <li class="sub-link"><a href="#">Outdoor Lounges</a></li>
            <li class="sub-link"><a href="#">Outdoor Dining</a></li>
            <li class="sub-link"><a href="#">Outdoor Umbrellas &amp; Accessries</a></li>
            <li class="sub-link"><a href="#">Wood Fireplaces</a></li>
            <li class="sub-link"><a href="#">Gas Fireplaces</a></li>
            <li class="sub-link"><a href="#">Ethanol Fireplaces</a></li>
            <li class="sub-link"><a href="#">Ethanol Fireplaces</a></li>
            <li class="sub-link"><a href="#">Weber Charcoal BBQs</a></li>
            <li class="sub-link"><a href="#">Weber Premium Gas BBQs</a></li>
            <li class="sub-link"><a href="#">Weber Qs</a></li>
            <li class="sub-link"><a href="#">Weber Elelectic BBQs</a></li>
            <li class="sub-link"><a href="#">Clearance Store</a></li>
        </ul>
    </div>
</div> -->

<!--


----------------------------------------------------------------------------------------------
<li><a href="https://www.facebook.com"><i class="fab fa-facebook-f"></i></a></li>
<li><a href="https://www.instagram.com"><i class="fab fa-instagram"></i></a></li>
<li><a href="https://www.twitter.com"><i class="fab fa-twitter"></i></a></li>
<li><a href="https://www.youtube.com"><i class="fab fa-youtube"></i></a></li>
<li><a href="https://www.printerest.com"><i class="fab fa-pinterest"></i></a></li>

-->

