<div class="footer-showroom">
    <?php
        echo $block->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('footer-showroom')
            ->toHtml();
    ?>
</div>

<div class="footer-showroom-mobile">
    <?php
        echo $block->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('footer-showroom-mobile')
            ->toHtml();
    ?>
</div>