<div class="footer-top">
    <?php
        echo $block->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('footer-top')
            ->toHtml();
    ?>
</div>

<!-- <div class="sub-custom-footer">
    <div class="sub-footer-top">
        <i class="fas fa-truck"></i><span>We ship australia wide! </span>
    </div>
    <div class="sub-footer-top">
        <i class="fas fa-map-marker-alt"></i><span>Find a store</span>
    </div>
    <div class="sub-footer-top">
        <i class="fas fa-dollar-sign"></i><span>Money back guarantee </span>
    </div>
    <div class="sub-footer-top">
        <i class="fas fa-envelope"></i><span>Contact us</span>
    </div>
</div> -->