<li class="social-link">
    <?php
        echo $block->getLayout()
                    ->createBlock('Magento\Cms\Block\Block')
                    ->setBlockId('social-link-facebook')
                    ->toHtml();
    ?>
</li>

<li class="social-link">
    <?php
        echo $block->getLayout()
                    ->createBlock('Magento\Cms\Block\Block')
                    ->setBlockId('social-link-instagram')
                    ->toHtml();
    ?>
</li>



