<div class="row">
    <div class="col-2">
        <div class="buttons">
            <h2 class="title">Buttons</h2>
            <div class="row">
                <div class="col-3" style="width: 30%;">
                    <a class="action primary" href="#"><span>ADD TO CART</span></a>
                    <a class="action primary new" href="#" style="margin-top:10px"><span>ADD TO CART</span></a>
                </div>
                <div class="col-3 " style="width: 25%;">
                    <a href="#" class="action new-button"><span>STANDARD</span></a>
                    <a href="#" class="action new-button secondary" style="margin-top:10px"><span>STANDARD</span></a>
                </div>
                <div class="col-3">
                    <div class="field qty">
                        <div class="control">
                            <input type="number" name="qty" id="qty" min="0" value="0" title="Qty" class="input-text qty" />
                            <input type="number" name="qty" id="qty" min="0" value="0" title="Qty" class="input-text qty" style="margin-top:10px" />                         
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="buttons-input">
            <h2 class="title">Checkboxes & Radio Buttons</h2>
            <div class="row">
                <div class="col">
                    <input type="checkbox" id="ck1" checked name="cb" value="">
                    <label for="ck1"> Ticked</label><br />
                    <input type="checkbox" id="ck2" name="cb" value="">
                    <label for="ck2"> Not Ticked</label><br />
                    <input type="checkbox" id="ck3" disabled="disabled" checked name="cb" value="">
                    <label for="ck3"> Ticked, Disabled</label><br />
                    <input type="checkbox" id="ck4" disabled="disabled" name="cb" value="">
                    <label for="ck4"> Disabled</label>
                </div>
                <div class="col">
                    <input type="radio" id="rd1" checked name="rd" value="" />
                    <label for="rd1"> Selected</label><br />
                    <input type="radio" id="rd2" name="rd" value="">
                    <label for="rd2"> Not Selected</label><br />
                    <input type="radio" id="rd3" disabled="disabled" checked name="rd2" value="" />
                    <label for="rd3"> Selected, Disabled</label><br />
                    <input type="radio" id="rd4" disabled="disabled" name="rd2" value="" />
                    <label for="rd4"> Disabled</label>
                </div>
            </div>
        </div>

        <div class="input-field">
            <h2 class="title">Input Fields</h2>
            <form class="form" action="#" method="post" id="my-form" data-hasrequired="* Required Fields">
                <fieldset class="fieldset">
                    <div class="input" style="width: 50%;">
                        <div class="control">
                            <select class="input" name="select" id="select">
                                <option value="">Dropdown field</option>
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                            </select>
                        </div><br />
                        <div class="field name firstname required">
                            <label class="label" for="firstname"><span>First Name</span></label>
                            <div class="control">
                                <input type="text" id="firstname" name="firstname" value="" title="First Name" data-validate='{"required":true, "minlength":10}'>
                            </div>
                        </div>

                        <div class="field name password required">
                            <label class="label" for="password"><span>Password</span></label>
                            <div class="control">
                                <input type="password" id="lastname" name="lastname" value="" title="Last Name" data-validate='{"required":true, "minlength":10}'>
                            </div>
                        </div>

                        <div class="field required">
                            <label for="email_address" class="label"><span>Email Address</span></label data-validate='{"required":true, "minlength":10}'>
                            <div class="control">
                                <input type="email" name="email" id="email_address" value="" title="Email Address">
                            </div>
                        </div>
                    </div>
                </fieldset>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button type="submit" title="Submit" class="action new-button secondary">
                            <span>Submit</span>
                        </button>
                    </div>
                </div>
            </form>
        </div>
        <dl class="example-sections-1" role="tablist">

            <dt class="item title active" data-section="title">
                <a class="switch" data-toggle="switch" href="#product.info.description">Details</a>
            </dt>
            <dd class="item content active" data-section="content">
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
            </dd>

            <dt class="item title" data-section="title">
                <a class="switch" data-toggle="switch" href="#product_tags">Tags</a>
            </dt>
            <dd class="item content" data-section="content">
                <p>It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
            </dd>

            <dt class="item title" data-section="title">
                <a class="switch" data-toggle="switch" href="#product_reviews">Reviews</a>
            </dt>
            <dd class="item content" data-section="content">
                <p>It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
            </dd>
        </dl>

    </div>




    <div class="col-2">
        <div class="alt" style="padding-left: 20px" ;>
            <div class="alert">
                <h2 class="title">Alerts</h2>
                <div class="alert-success">
                    <p>Product has been added to your shopping bag</p>
                </div>
                <div class="alert-error">
                    <p>Invalid username or password</p>
                </div>
            </div>

            <div class="typography">
                <h2 class="title">Typography</h2>
                <p>Open Sans Regular - 13px / 20px
                <p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                    Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                    Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
                    Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                </br>
                </br>
                <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium,
                    totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
                </br>
                </br>
                <a href="#">Text link</a>
                </br>
                <a href="#">Text link hover</a>
                </br>
                </br>
                </br>
                <h1>h1 Lora Regular - 32px</h1>
                <h2>h2 Lora Regular - 24px</h2>
                <h3>h3 Lora Regular - 18px</h3>
                <h4>h4 Lora Regular - 15px</h4>
            </div>

            <div class="misc">
                <h2 class="title">Misc</h2>
            </div>

        </div>

    </div>

</div>

<script type="text/x-magento-init">
    {
        "#my-form": {
            "validation": {}
        }
    }
</script>